In [2]:
import pandas as pd

In [3]:
# Before execute this code, edit manually this excel like 'Changing Column name - NOM_le_plus_voté' and '_x, _y' delete ...
excel_final=pd.ExcelFile('DataFrame pour les législatives (2eme tour de 2002)/Les tendances de votes avec cordonnées pour les législatives (2eme tour de 2002)_final.xlsx')

In [4]:
df_commune = pd.read_excel(excel_final)

In [5]:
df_commune

,commune_code,N° de bureau de vote,longitude,latitude,Inscrits,Votants,Exprimés,Nom du candidat,Prénom du candidat,Code nuance du candidat,...,Nom du candidat.3,Prénom du candidat.3,Code nuance du candidat .3,Nombre de voix du candidat.3,% Voix/Exp.3,NOM_le_plus_voté,PRENOM_le_plus_voté,NUANCE_le_plus_voté,Nombre de voix du candidat_y,% Voix/Exp_le_plus_voté
0,1001,1.0,4.920902,46.150784,568,314,307,VOISIN,MICHEL,UMP,...,NaN,NaN,NaN,NaN,NaN,VOISIN,MICHEL,UMP,188,61.237785
1,1002,1.0,5.423436,46.007249,195,133,122,GUICHON,LUCIEN,UMP,...,NaN,NaN,NaN,NaN,NaN,GUICHON,LUCIEN,UMP,74,60.655738
2,1004,1.0,5.348146,45.960048,1393,726,695,GUICHON,LUCIEN,UMP,...,NaN,NaN,NaN,NaN,NaN,GUICHON,LUCIEN,UMP,378,54.388489
3,1004,2.0,5.348146,45.960048,1513,789,760,GUICHON,LUCIEN,UMP,...,NaN,NaN,NaN,NaN,NaN,GUICHON,LUCIEN,UMP,418,55.000000
4,1004,3.0,5.364613,45.955227,1328,617,590,GUICHON,LUCIEN,UMP,...,NaN,NaN,NaN,NaN,NaN,DRUT-GORJU,ELIANE,SOC,310,52.542373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43632,95680,8.0,2.412123,48.999556,470,258,247,STRAUSS KAHN,DOMINIQUE,SOC,...,NaN,NaN,NaN,NaN,NaN,STRAUSS KAHN,DOMINIQUE,SOC,140,56.680162
43633,95680,9.0,2.395384,49.003751,1117,483,465,STRAUSS KAHN,DOMINIQUE,SOC,...,NaN,NaN,NaN,NaN,NaN,STRAUSS KAHN,DOMINIQUE,SOC,335,72.043011
43634,95680,10.0,2.395384,49.003751,861,374,352,STRAUSS KAHN,DOMINIQUE,SOC,...,NaN,NaN,NaN,NaN,NaN,STRAUSS KAHN,DOMINIQUE,SOC,209,59.375000
43635,95682,1.0,2.390021,49.072537,93,60,57,BLAZY,J.PIERRE,SOC,...,NaN,NaN,NaN,NaN,NaN,HERMANVILLE,ELISABETH,UMP,31,54.385965
43636,95690,1.0,1.835615,49.102958,252,185,178,HOUILLON,PHILIPPE,UMP,...,NaN,NaN,NaN,NaN,NaN,HOUILLON,PHILIPPE,UMP,127,71.348315

In [12]:
df_commune[df_commune['% Voix/Exp.2'].notnull()]

,commune_code,N° de bureau de vote,longitude,latitude,Inscrits,Votants,Exprimés,Nom du candidat,Prénom du candidat,Code nuance du candidat,...,Nom du candidat.3,Prénom du candidat.3,Code nuance du candidat .3,Nombre de voix du candidat.3,% Voix/Exp.3,NOM_le_plus_voté,PRENOM_le_plus_voté,NUANCE_le_plus_voté,Nombre de voix du candidat_y,% Voix/Exp_le_plus_voté
2326,6088,101.0,7.258954,43.695620,923,475,466,MARLAND,MURIEL,UMP,...,NaN,NaN,NaN,NaN,NaN,MARLAND,MURIEL,UMP,214,45.922747
2327,6088,102.0,7.258954,43.695620,969,525,519,MARLAND,MURIEL,UMP,...,NaN,NaN,NaN,NaN,NaN,MARLAND,MURIEL,UMP,228,43.930636
2328,6088,103.0,7.258954,43.695620,967,541,538,MARLAND,MURIEL,UMP,...,NaN,NaN,NaN,NaN,NaN,MARLAND,MURIEL,UMP,213,39.591078
2329,6088,104.0,7.269771,43.702070,821,407,404,MARLAND,MURIEL,UMP,...,NaN,NaN,NaN,NaN,NaN,MARLAND,MURIEL,UMP,168,41.584158
2330,6088,105.0,7.269771,43.702070,992,572,565,MARLAND,MURIEL,UMP,...,NaN,NaN,NaN,NaN,NaN,MARLAND,MURIEL,UMP,256,45.309735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41354,92044,27.0,2.295453,48.892280,1261,907,891,BALKANY,PATRICK,DVD,...,NaN,NaN,NaN,NaN,NaN,CHAZEAUX DE,OLIVIER,UMP,365,40.965208
41355,92044,28.0,2.296535,48.895270,922,651,643,BALKANY,PATRICK,DVD,...,NaN,NaN,NaN,NaN,NaN,BALKANY,PATRICK,DVD,244,37.947123
41356,92044,29.0,2.300545,48.893940,1081,786,779,BALKANY,PATRICK,DVD,...,NaN,NaN,NaN,NaN,NaN,BALKANY,PATRICK,DVD,338,43.388960
41357,92044,30.0,2.296298,48.892947,1053,723,705,BALKANY,PATRICK,DVD,...,NaN,NaN,NaN,NaN,NaN,BALKANY,PATRICK,DVD,272,38.581560
41358,92044,31.0,2.295442,48.893461,1236,920,908,BALKANY,PATRICK,DVD,...,NaN,NaN,NaN,NaN,NaN,CHAZEAUX DE,OLIVIER,UMP,383,42.180617

In [13]:
# number = 3, (2 ~ 0)

def makeDataFrame(number):
    global df_commune
    
    # 1) Make a new DataFrame 
    index_list = df_commune[df_commune['Nom du candidat.'+str(number)].notnull()].index.tolist()
    globals()['df_voix_'+str(number)] = pd.DataFrame(df_commune, index=index_list)
    
    # 2) df_commune - df_new_dataframe
    df = pd.concat([df_commune, globals()['df_voix_'+str(number)]])
    df = df.drop_duplicates(keep=False)
    df_commune = df
    
    # 3) Make Excel File
    globals()['df_voix_'+str(number)].to_excel('DataFrame pour les législatives (2eme tour de 2002)/df_voix_'+str(number)+'.xlsx')

In [14]:
for number in range(3,1,-1):
    if number == 2:
        df_commune.to_excel('DataFrame pour les législatives (2eme tour de 2002)/df_voix_2_to_0.xlsx')
        break
    makeDataFrame(number)