In [1]:
import pandas as pd

In [2]:
excel_final=pd.ExcelFile('DataFrame pour les législatives (2eme tour de 2012)/Les tendances de votes avec cordonnées pour les législatives (2eme tour de 2012)_final.xlsx')

In [3]:
df_commune = pd.read_excel(excel_final)

In [4]:
df_commune

,Unnamed: 0,commune_code,N° de bureau de vote,longitude_x,latitude,Inscrits,Votants,Exprimés,Nom du candidat,Prénom du candidat,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,NOM_le_plus_voté,PRENOM_le_plus_voté,NUANCE_le_plus_voté,Nombre de voix du candidat_y,% Voix/Exp_le_plus_voté
0,0.0,1001.0,1.0,4.920902,46.150784,595.0,330.0,317.0,LACROIX,Guillaume,...,NaN,NaN,NaN,NaN,NaN,VOISIN,Michel,UMP,175.0,55.205047
1,1.0,1002.0,1.0,5.423436,46.007249,216.0,130.0,122.0,EXPOSITO,Josiane,...,NaN,NaN,NaN,NaN,NaN,ABAD,Damien,UMP,66.0,54.098361
2,2.0,1004.0,1.0,5.348146,45.960048,1029.0,536.0,521.0,EXPOSITO,Josiane,...,NaN,NaN,NaN,NaN,NaN,EXPOSITO,Josiane,SOC,286.0,54.894434
3,3.0,1004.0,2.0,5.348146,45.960048,1071.0,608.0,584.0,EXPOSITO,Josiane,...,NaN,NaN,NaN,NaN,NaN,ABAD,Damien,UMP,339.0,58.047945
4,4.0,1004.0,3.0,5.364613,45.955227,1019.0,588.0,559.0,EXPOSITO,Josiane,...,NaN,NaN,NaN,NaN,NaN,ABAD,Damien,UMP,291.0,52.057245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_commune[df_commune['Unnamed: 33'].notnull()]

Empty DataFrame
Columns: [Unnamed: 0, commune_code, N° de bureau de vote, longitude_x, latitude, Inscrits, Votants, Exprimés, Nom du candidat, Prénom du candidat, Code nuance du candidat, Nombre de voix du candidat, % Voix/Exp, Nom du candidat.1, Prénom du candidat.1, Code nuance du candidat.1, Nombre de voix du candidat.1, % Voix/Exp.1, Nom du candidat.2, Prénom du candidat.2, Code nuance du candidat.2, Nombre de voix du candidat.2, % Voix/Exp.2, Nom du candidat.3, Prénom du candidat.3, Code nuance du candidat.3, Nombre de voix du candidat.3, % Voix/Exp.3, Unnamed: 27, Unnamed: 28, Unnamed: 29, Unnamed: 30, Unnamed: 31, Unnamed: 32, Unnamed: 33, NOM_le_plus_voté, PRENOM_le_plus_voté, NUANCE_le_plus_voté, Nombre de voix du candidat_y, % Voix/Exp_le_plus_voté]
Index: []

[0 rows x 40 columns]

In [38]:
# number = 26, 25, 24, 23, ... , 7

def makeDataFrame(number):
    global df_commune
    
    # 1) Make a new DataFrame 
    index_list = df_commune[df_commune['Nom du candidat.'+str(number)].notnull()].index.tolist()
    globals()['df_voix_'+str(number)] = pd.DataFrame(df_commune, index=index_list)
    
    # 2) df_commune - df_new_dataframe
    df = pd.concat([df_commune, globals()['df_voix_'+str(number)]])
    df = df.drop_duplicates(keep=False)
    df_commune = df
    
    # 3) Make Excel File
    globals()['df_voix_'+str(number)].to_excel('DataFrame pour les législatives (1er tour de 2012)/df_voix_'+str(number)+'.xlsx')

In [39]:
for number in range(26,5,-1):
    if number == 6:
        df_commune.to_excel('DataFrame pour les législatives (1er tour de 2012)/df_voix_6_to_0.xlsx')
    makeDataFrame(number)