In [1]:
import pandas as pd

In [2]:
excel_final=pd.ExcelFile('DataFrame pour les législatives (1er tour de 2012)/3)Les tendances de votes avec cordonnées pour les législatives (1er tour de 2012)_final.xlsx')

In [3]:
df_commune = pd.read_excel(excel_final)

In [4]:
df_commune

,Unnamed: 0,commune_code,N° de bureau de vote,longitude,latitude,Inscrits,Votants,Exprimés,Nom du candidat,Prénom du candidat,...,% Voix/Exp.25,Nom du candidat.26,Prénom du candidat.26,Code nuance du candidat.26,Nombre de voix du candidat.26,% Voix/Exp.26,NOM_le_plus_voté,PRENOM_le_plus_voté,NUANCE_le_plus_voté,% Voix/Exp_le_plus_voté
0,0,1001,1,4.920902,46.150784,595,370,364,LACROIX,Guillaume,...,0.0,NaN,NaN,NaN,NaN,0.0,VOISIN,Michel,UMP,35.439560
1,1,1002,1,5.423436,46.007249,216,138,133,SOKOLOWSKI,Patrick,...,0.0,NaN,NaN,NaN,NaN,0.0,EXPOSITO,Josiane,SOC,34.586466
2,2,1004,1,5.348146,45.960048,1029,531,528,SOKOLOWSKI,Patrick,...,0.0,NaN,NaN,NaN,NaN,0.0,EXPOSITO,Josiane,SOC,37.500000
3,3,1004,2,5.348146,45.960048,1071,589,578,SOKOLOWSKI,Patrick,...,0.0,NaN,NaN,NaN,NaN,0.0,ABAD,Damien,UMP,34.602076
4,4,1004,3,5.364613,45.955227,1019,608,601,SOKOLOWSKI,Patrick,...,0.0,NaN,NaN,NaN,NaN,0.0,EXPOSITO,Josiane,SOC,34.442596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51397,51397,95680,11,2.387895,49.006733,1223,488,473,ATONGA,Armand,...,0.0,NaN,NaN,NaN,NaN,0.0,PUPPONI,François,SOC,43.128964
51398,51398,95680,12,2.415228,49.001856,950,438,422,ATONGA,Armand,...,0.0,NaN,NaN,NaN,NaN,0.0,PUPPONI,François,SOC,48.104265
51399,51399,95680,13,2.395384,49.003751,658,236,225,ATONGA,Armand,...,0.0,NaN,NaN,NaN,NaN,0.0,PUPPONI,François,SOC,63.555556
51400,51400,95682,1,2.390021,49.072537,95,72,72,BLAZY,Jean-Pierre,...,0.0,NaN,NaN,NaN,NaN,0.0,BLAZY,Jean-Pierre,SOC,43.055556
51401,51401,95690,1,1.835615,49.102958,277,186,185,GILIBERT,Brigitte,...,0.0,NaN,NaN,NaN,NaN,0.0,HOUILLON,Philippe,UMP,45.945946

In [37]:
df_commune[df_commune['Nom du candidat.6'].notnull()]

,Unnamed: 0,commune_code,N° de bureau de vote,longitude,latitude,Inscrits,Votants,Exprimés,Nom du candidat,Prénom du candidat,...,% Voix/Exp.25,Nom du candidat.26,Prénom du candidat.26,Code nuance du candidat.26,Nombre de voix du candidat.26,% Voix/Exp.26,NOM_le_plus_voté,PRENOM_le_plus_voté,NUANCE_le_plus_voté,% Voix/Exp_le_plus_voté
0,0,1001,1,4.920902,46.150784,595,370,364,LACROIX,Guillaume,...,0.0,NaN,NaN,NaN,NaN,0.0,VOISIN,Michel,UMP,35.439560
1,1,1002,1,5.423436,46.007249,216,138,133,SOKOLOWSKI,Patrick,...,0.0,NaN,NaN,NaN,NaN,0.0,EXPOSITO,Josiane,SOC,34.586466
2,2,1004,1,5.348146,45.960048,1029,531,528,SOKOLOWSKI,Patrick,...,0.0,NaN,NaN,NaN,NaN,0.0,EXPOSITO,Josiane,SOC,37.500000
3,3,1004,2,5.348146,45.960048,1071,589,578,SOKOLOWSKI,Patrick,...,0.0,NaN,NaN,NaN,NaN,0.0,ABAD,Damien,UMP,34.602076
4,4,1004,3,5.364613,45.955227,1019,608,601,SOKOLOWSKI,Patrick,...,0.0,NaN,NaN,NaN,NaN,0.0,EXPOSITO,Josiane,SOC,34.442596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51397,51397,95680,11,2.387895,49.006733,1223,488,473,ATONGA,Armand,...,0.0,NaN,NaN,NaN,NaN,0.0,PUPPONI,François,SOC,43.128964
51398,51398,95680,12,2.415228,49.001856,950,438,422,ATONGA,Armand,...,0.0,NaN,NaN,NaN,NaN,0.0,PUPPONI,François,SOC,48.104265
51399,51399,95680,13,2.395384,49.003751,658,236,225,ATONGA,Armand,...,0.0,NaN,NaN,NaN,NaN,0.0,PUPPONI,François,SOC,63.555556
51400,51400,95682,1,2.390021,49.072537,95,72,72,BLAZY,Jean-Pierre,...,0.0,NaN,NaN,NaN,NaN,0.0,BLAZY,Jean-Pierre,SOC,43.055556
51401,51401,95690,1,1.835615,49.102958,277,186,185,GILIBERT,Brigitte,...,0.0,NaN,NaN,NaN,NaN,0.0,HOUILLON,Philippe,UMP,45.945946

In [38]:
# number = 26, 25, 24, 23, ... , 7

def makeDataFrame(number):
    global df_commune
    
    # 1) Make a new DataFrame 
    index_list = df_commune[df_commune['Nom du candidat.'+str(number)].notnull()].index.tolist()
    globals()['df_voix_'+str(number)] = pd.DataFrame(df_commune, index=index_list)
    
    # 2) df_commune - df_new_dataframe
    df = pd.concat([df_commune, globals()['df_voix_'+str(number)]])
    df = df.drop_duplicates(keep=False)
    df_commune = df
    
    # 3) Make Excel File
    globals()['df_voix_'+str(number)].to_excel('DataFrame pour les législatives (1er tour de 2012)/df_voix_'+str(number)+'.xlsx')

In [39]:
for number in range(26,5,-1):
    if number == 6:
        df_commune.to_excel('DataFrame pour les législatives (1er tour de 2012)/df_voix_6_to_0.xlsx')
    makeDataFrame(number)